import { PLUSH_GOLD_BILLING_ENABLED, PLUSH_GOLD_FEATURES, goldPreviewSummary } from '../plush-gold.js';
const card={padding:15,borderRadius:20,border:'1px solid var(--pl-theme-line)',background:'var(--pl-theme-surface)',color:'var(--pl-theme-ink)',marginBottom:12};
const free=['Tasks, routines, habits, Today and calendar','Care tools, check-ins and your comfort profile','Basic PlushGuide and Guardian support','Sharing boundaries, accessibility and privacy controls','Reminders, backup, sync and basic data export','My Reset and making a rough day smaller'];
const planned=['PlushGuide+ and Routine Builder+','Opt-in Smart Day Autopilot and deeper personalization','Comfort Kit learning and searchable long-term memory','Scheduled Guardian check-ins and support summaries','Context-aware check-ins and custom automations','Optional sleep/activity integrations','Advanced widgets, watch controls and personal reports'];
export function PlushGoldPreview(){
  const available=goldPreviewSummary().features.filter(f=>f.status==='available'&&f.id!=='priority_history_protection');
  return <div aria-label="PlushLife Plus plan"><section style={card}><h3 style={{margin:0,fontSize:20}}>✨ PlushLife Plus</h3><p style={{fontSize:15,lineHeight:1.5}}>Free PlushLife helps you take care of yourself. PlushLife Plus learns how you live and quietly helps make life easier.</p><b style={{fontSize:14}}>Everything is included free for now.</b><p style={{fontSize:13,color:'var(--pl-theme-muted)'}}>{PLUSH_GOLD_BILLING_ENABLED?'Billing active':'Billing off · free preview'}</p></section>
  <section style={card}><h4 style={{margin:'0 0 8px',fontSize:17}}>💜 Always in Free</h4><ul style={{fontSize:14,lineHeight:1.7,paddingLeft:20}}>{free.map(text=><li key={text}>{text}</li>)}</ul></section>
  <section style={card}><h4 style={{margin:'0 0 8px',fontSize:17}}>🌱 Smart help available today</h4><ul style={{fontSize:14,lineHeight:1.7,paddingLeft:20}}>{available.map(f=><li key={f.id}>{f.label.replace(/Gold/g,'Plus')}</li>)}</ul></section>
  <details style={card}><summary style={{minHeight:44,display:'flex',alignItems:'center',fontSize:17,fontWeight:800,cursor:'pointer'}}>Where Plus is going</summary><p style={{fontSize:14}}>These features are planned; they are not subscriptions or promises of features available today.</p><ul style={{fontSize:14,lineHeight:1.7,paddingLeft:20}}>{planned.map(text=><li key={text}>{text}</li>)}</ul></details>
  <p style={{fontSize:14,lineHeight:1.5,color:'var(--pl-theme-muted)'}}>One simple optional subscription when purchasing is ready. Your themes, plush accessories, essential support, and privacy stay outside paid upgrades.</p></div>;
}
export {PLUSH_GOLD_FEATURES};
